-- Fase 1: Fundação multi-tenant (Auth + RLS)
-- Rode este arquivo inteiro no SQL Editor do Supabase (dashboard > SQL Editor > New query).

-- 1. Tabela suppliers (cadastro de fornecedores)
create table if not exists suppliers (
  id uuid primary key default gen_random_uuid(),
  auth_user_id uuid unique references auth.users(id) on delete set null,
  business_name text not null,
  slug text not null unique,
  whatsapp_number text not null,
  cart_greeting text not null default 'Olá! Gostaria de fazer um pedido:',
  theme_color text,
  created_at timestamptz not null default now()
);

-- 2. Tabela wines (catálogo), agora multi-tenant via supplier_id
create table if not exists wines (
  id bigint generated by default as identity primary key,
  supplier_id uuid not null references suppliers(id) on delete cascade,
  name text not null,
  type text not null,
  origin text not null,
  price numeric not null,
  promo numeric,
  tags text[] not null default '{}',
  created_at timestamptz not null default now()
);

create index if not exists wines_supplier_id_idx on wines (supplier_id);

-- 3. RLS
alter table suppliers enable row level security;
alter table wines enable row level security;

-- suppliers: cada fornecedor só vê/edita a própria linha (leitura pública passa pela view abaixo)
drop policy if exists "supplier selects own row" on suppliers;
create policy "supplier selects own row" on suppliers
  for select using (auth.uid() = auth_user_id);

drop policy if exists "supplier updates own row" on suppliers;
create policy "supplier updates own row" on suppliers
  for update using (auth.uid() = auth_user_id)
  with check (auth.uid() = auth_user_id);

-- Não há policy de INSERT/DELETE para authenticated: novos fornecedores são
-- cadastrados via SQL Editor (dono do projeto), não pelo app. Ver Fase 3.

-- view pública com só os campos necessários para o catálogo (Fase 2/3),
-- roda com privilégio do dono da view, então ignora a RLS de suppliers de propósito.
create or replace view suppliers_public as
  select id, business_name, slug, whatsapp_number, cart_greeting, theme_color
  from suppliers;

grant select on suppliers_public to anon, authenticated;

-- wines: leitura pública liberada (é vitrine, não é dado sensível);
-- escrita restrita ao próprio supplier_id do usuário autenticado.
drop policy if exists "public reads wines" on wines;
create policy "public reads wines" on wines
  for select using (true);

drop policy if exists "supplier inserts own wines" on wines;
create policy "supplier inserts own wines" on wines
  for insert with check (
    supplier_id = (select id from suppliers where auth_user_id = auth.uid())
  );

drop policy if exists "supplier updates own wines" on wines;
create policy "supplier updates own wines" on wines
  for update using (
    supplier_id = (select id from suppliers where auth_user_id = auth.uid())
  ) with check (
    supplier_id = (select id from suppliers where auth_user_id = auth.uid())
  );

drop policy if exists "supplier deletes own wines" on wines;
create policy "supplier deletes own wines" on wines
  for delete using (
    supplier_id = (select id from suppliers where auth_user_id = auth.uid())
  );
