-- Seed: catálogo atual (134 itens) para o fornecedor de teste A
with target as (
  select id from suppliers where slug = 'fornecedor-teste-a'
)
insert into wines (supplier_id, name, type, origin, price, promo, tags)
select target.id, v.name, v.type, v.origin, v.price, v.promo, v.tags
from target, (values
  ('Alma Negra Blanc de Blancs', 'Espumante', 'ARGENTINA', 145, 129, ARRAY['promo']),
  ('Chandon Extra Brut', 'Espumante', 'ARGENTINA', 100, 90, ARRAY['promo']),
  ('4000 Black Blend', 'Tinto', 'ARGENTINA', 120, NULL, ARRAY[]::text[]),
  ('4000 Malbec', 'Tinto', 'ARGENTINA', 120, NULL, ARRAY[]::text[]),
  ('Achaval Ferrer Malbec', 'Tinto', 'ARGENTINA', 120, NULL, ARRAY[]::text[]),
  ('Achaval Ferrer Quimera', 'Tinto', 'ARGENTINA', 210, 194, ARRAY['promo']),
  ('Alamos Malbec', 'Tinto', 'ARGENTINA', 70, 59, ARRAY['promo']),
  ('Alamos Reserve Malbec', 'Tinto', 'ARGENTINA', 75, NULL, ARRAY[]::text[]),
  ('Alma Negra Tinto', 'Tinto', 'ARGENTINA', 140, 129, ARRAY['promo']),
  ('Amalaya Rosé', 'Rosé', 'ARGENTINA', 79, NULL, ARRAY[]::text[]),
  ('Anaia Gran Reserva Malbec', 'Tinto', 'ARGENTINA', 149, NULL, ARRAY[]::text[]),
  ('Angélica Zapata Alta Cabernet Franc', 'Tinto', 'ARGENTINA', 135, 129, ARRAY['promo']),
  ('Angélica Zapata Alta Cabernet Sauvignon', 'Tinto', 'ARGENTINA', 135, 129, ARRAY['promo']),
  ('Angélica Zapata Alta Chardonnay', 'Branco', 'ARGENTINA', 140, NULL, ARRAY[]::text[]),
  ('Angélica Zapata Alta Malbec', 'Tinto', 'ARGENTINA', 155, 149, ARRAY['promo']),
  ('Angélica Zapata Alta Merlot', 'Tinto', 'ARGENTINA', 135, 129, ARRAY['promo']),
  ('Antonieta Rosé Pinot Noir', 'Rosé', 'ARGENTINA', 149, NULL, ARRAY[]::text[]),
  ('Barrabas Cabernet Franc by Judas', 'Tinto', 'ARGENTINA', 310, 259, ARRAY['promo']),
  ('Bramare Chardonnay Valle De Uco', 'Branco', 'ARGENTINA', 210, NULL, ARRAY[]::text[]),
  ('Bramare Malbec Luján de Cuyo', 'Tinto', 'ARGENTINA', 240, NULL, ARRAY[]::text[]),
  ('Bressia Lágrima Canela Chardonnay', 'Branco', 'ARGENTINA', 150, 139, ARRAY['promo']),
  ('Bressia Piel Negra Pinot Noir', 'Tinto', 'ARGENTINA', 150, NULL, ARRAY[]::text[]),
  ('Catena Zapata Birth Of Cabernet', 'Tinto', 'ARGENTINA', 490, 419, ARRAY['promo']),
  ('Catena Zapata Malbec Argentino', 'Tinto', 'ARGENTINA', 325, NULL, ARRAY[]::text[]),
  ('Clos De Los Siete', 'Tinto', 'ARGENTINA', 119, NULL, ARRAY[]::text[]),
  ('Cobos Vinculum Chardonnay', 'Branco', 'ARGENTINA', 259, NULL, ARRAY[]::text[]),
  ('Cobos Vinculum Malbec', 'Tinto', 'ARGENTINA', 349, NULL, ARRAY[]::text[]),
  ('DV Catena Cabernet Malbec', 'Tinto', 'ARGENTINA', 85, 79, ARRAY['promo']),
  ('DV Catena Chardonnay', 'Branco', 'ARGENTINA', 110, NULL, ARRAY[]::text[]),
  ('DV Catena Malbec Malbec', 'Tinto', 'ARGENTINA', 115, NULL, ARRAY[]::text[]),
  ('DV Catena Tinto Histórico', 'Tinto', 'ARGENTINA', 175, 150, ARRAY['promo']),
  ('El Enemigo Bonarda', 'Tinto', 'ARGENTINA', 135, 129, ARRAY['promo']),
  ('El Enemigo Cabernet Franc', 'Tinto', 'ARGENTINA', 135, 129, ARRAY['promo']),
  ('El Enemigo Chardonnay', 'Branco', 'ARGENTINA', 135, 129, ARRAY['promo']),
  ('El Enemigo Malbec', 'Tinto', 'ARGENTINA', 135, 129, ARRAY['promo']),
  ('Enzo Bianchi Gran Malbec', 'Tinto', 'ARGENTINA', 359, NULL, ARRAY[]::text[]),
  ('Fabre Montmayou Gran Reserva Cabernet Sauvignon', 'Tinto', 'ARGENTINA', 120, 104, ARRAY['promo']),
  ('Gran Cordero Malbec', 'Tinto', 'ARGENTINA', 79, 72, ARRAY['promo']),
  ('Gran Enemigo Cepillo', 'Tinto', 'ARGENTINA', 220, NULL, ARRAY[]::text[]),
  ('Gran Enemigo Chacayes', 'Tinto', 'ARGENTINA', 220, NULL, ARRAY[]::text[]),
  ('Gran Enemigo Gualtallary', 'Tinto', 'ARGENTINA', 285, NULL, ARRAY[]::text[]),
  ('Hermandad Blend', 'Tinto', 'ARGENTINA', 140, 129, ARRAY['promo']),
  ('Hermandad Blend Magnum 1,5L', 'Tinto', 'ARGENTINA', 275, 249, ARRAY['promo']),
  ('Huentala Gran Sombrero Cabernet Franc', 'Tinto', 'ARGENTINA', 95, NULL, ARRAY[]::text[]),
  ('Huentala Gran Sombrero Malbec', 'Tinto', 'ARGENTINA', 95, NULL, ARRAY[]::text[]),
  ('José Zuccardi Malbec', 'Tinto', 'ARGENTINA', 289, NULL, ARRAY[]::text[]),
  ('Judas Malbec', 'Tinto', 'ARGENTINA', 330, NULL, ARRAY[]::text[]),
  ('Kaiken Ultra Chardonnay', 'Branco', 'ARGENTINA', 109, NULL, ARRAY[]::text[]),
  ('Kaiken Ultra Merlot', 'Tinto', 'ARGENTINA', 109, NULL, ARRAY[]::text[]),
  ('Kaiken Ultra Pinot Noir', 'Tinto', 'ARGENTINA', 109, NULL, ARRAY[]::text[]),
  ('Kaiken Ultra Cabernet Sauvignon', 'Tinto', 'ARGENTINA', 109, NULL, ARRAY[]::text[]),
  ('Kalós Cru Gran Reserva Malbec', 'Tinto', 'ARGENTINA', 175, 159, ARRAY['promo']),
  ('La Azul El Buscapleito Cabernet Franc Reserva', 'Tinto', 'ARGENTINA', 110, 104, ARRAY['promo']),
  ('La Flor Malbec', 'Tinto', 'ARGENTINA', 80, NULL, ARRAY[]::text[]),
  ('La Linda Malbec', 'Tinto', 'ARGENTINA', 70, NULL, ARRAY[]::text[]),
  ('La Zulema Malbec', 'Tinto', 'ARGENTINA', 65, NULL, ARRAY[]::text[]),
  ('Los Intocables Bourbon Barrel Blend', 'Tinto', 'ARGENTINA', 75, NULL, ARRAY[]::text[]),
  ('Los Intocables Bourbon Barrel Cabernet Sauvignon', 'Tinto', 'ARGENTINA', 75, NULL, ARRAY[]::text[]),
  ('Los Intocables Bourbon Barrel Chardonnay', 'Branco', 'ARGENTINA', 75, NULL, ARRAY[]::text[]),
  ('Los Intocables Bourbon Barrel Malbec', 'Tinto', 'ARGENTINA', 75, NULL, ARRAY[]::text[]),
  ('Luigi Bosca Cabernet Sauvignon', 'Tinto', 'ARGENTINA', 90, NULL, ARRAY[]::text[]),
  ('Luigi Bosca Chardonnay', 'Branco', 'ARGENTINA', 90, NULL, ARRAY[]::text[]),
  ('Luigi Bosca Malbec', 'Tinto', 'ARGENTINA', 90, NULL, ARRAY[]::text[]),
  ('Malcriado Malbec', 'Tinto', 'ARGENTINA', 240, NULL, ARRAY[]::text[]),
  ('Matias Riccitelli Malbec 2017', 'Tinto', 'ARGENTINA', 250, 239, ARRAY['promo']),
  ('Mauricio Lorca Inspirado Cabernet', 'Tinto', 'ARGENTINA', 190, 164, ARRAY['promo']),
  ('Milamore', 'Tinto', 'ARGENTINA', 95, 89, ARRAY['promo']),
  ('Mosquita Muerta Blend de Blancas', 'Branco', 'ARGENTINA', 110, NULL, ARRAY[]::text[]),
  ('Nicasia Gran Blend', 'Tinto', 'ARGENTINA', 95, 84, ARRAY['promo']),
  ('Nicasia Red Blend Malbec', 'Tinto', 'ARGENTINA', 75, NULL, ARRAY[]::text[]),
  ('Nicolas Catena Zapata', 'Tinto', 'ARGENTINA', 340, NULL, ARRAY[]::text[]),
  ('Norton D.O.C Malbec', 'Tinto', 'ARGENTINA', 70, NULL, ARRAY[]::text[]),
  ('Pequeñas Producciones Malbec', 'Tinto', 'ARGENTINA', 140, NULL, ARRAY[]::text[]),
  ('Petit Caro Blend', 'Tinto', 'ARGENTINA', 199, NULL, ARRAY[]::text[]),
  ('Pilatos Malbec By Judas', 'Tinto', 'ARGENTINA', 159, NULL, ARRAY[]::text[]),
  ('Pispi Blend De Tintas', 'Tinto', 'ARGENTINA', 80, 74, ARRAY['promo']),
  ('Privado Reserva Bonarda', 'Tinto', 'ARGENTINA', 85, NULL, ARRAY[]::text[]),
  ('Privado Reserva Cabernet Franc', 'Tinto', 'ARGENTINA', 85, NULL, ARRAY[]::text[]),
  ('Privado Reserva Chardonnay', 'Branco', 'ARGENTINA', 85, NULL, ARRAY[]::text[]),
  ('Privado Reserva Malbec', 'Tinto', 'ARGENTINA', 85, NULL, ARRAY[]::text[]),
  ('Privado Reserva Pinot Noir', 'Tinto', 'ARGENTINA', 85, NULL, ARRAY[]::text[]),
  ('Pulenta Estate Rosé Merlot', 'Rosé', 'ARGENTINA', 125, 114, ARRAY['promo']),
  ('Pulenta Estate VI Sauvignon Blanc', 'Branco', 'ARGENTINA', 110, NULL, ARRAY[]::text[]),
  ('Pulenta Estate VIII Chardonnay', 'Branco', 'ARGENTINA', 120, NULL, ARRAY[]::text[]),
  ('Pulenta Estate XVI Pinot Gris', 'Branco', 'ARGENTINA', 120, NULL, ARRAY[]::text[]),
  ('Raquis Las Bases', 'Tinto', 'ARGENTINA', 270, 259, ARRAY['promo']),
  ('Rutini Cabernet Franc', 'Tinto', 'ARGENTINA', 130, NULL, ARRAY[]::text[]),
  ('Rutini Cabernet Franc Malbec', 'Tinto', 'ARGENTINA', 105, NULL, ARRAY[]::text[]),
  ('Rutini Chardonnay', 'Branco', 'ARGENTINA', 140, NULL, ARRAY[]::text[]),
  ('Rutini Malbec', 'Tinto', 'ARGENTINA', 155, NULL, ARRAY[]::text[]),
  ('Saint Felicien Malbec', 'Tinto', 'ARGENTINA', 75, NULL, ARRAY[]::text[]),
  ('Saint Felicien Chardonnay', 'Branco', 'ARGENTINA', 75, NULL, ARRAY[]::text[]),
  ('Salentein Numina Malbec', 'Tinto', 'ARGENTINA', 135, NULL, ARRAY[]::text[]),
  ('Septima Gran Reserva', 'Tinto', 'ARGENTINA', 195, NULL, ARRAY[]::text[]),
  ('Sottano Reserva Família Malbec Cabernet', 'Tinto', 'ARGENTINA', 105, NULL, ARRAY[]::text[]),
  ('Sottano Sin Reglas Assemblage', 'Tinto', 'ARGENTINA', 99, NULL, ARRAY[]::text[]),
  ('Sottano Sin Reglas Malbec', 'Tinto', 'ARGENTINA', 99, NULL, ARRAY[]::text[]),
  ('Susana Balbo BenMarco Expresivo', 'Tinto', 'ARGENTINA', 145, NULL, ARRAY[]::text[]),
  ('Terraza De Los Andes Reserva Malbec', 'Tinto', 'ARGENTINA', 120, NULL, ARRAY[]::text[]),
  ('Trumpeter Chardonnay', 'Branco', 'ARGENTINA', 70, NULL, ARRAY[]::text[]),
  ('Trumpeter Malbec', 'Tinto', 'ARGENTINA', 70, NULL, ARRAY[]::text[]),
  ('Zuccardi Concreto Malbec', 'Tinto', 'ARGENTINA', 245, 234, ARRAY['promo']),
  ('Zuccardi Poligonos Malbec', 'Tinto', 'ARGENTINA', 210, NULL, ARRAY[]::text[]),
  ('Zuccardi Q Cabernet Sauvignon', 'Tinto', 'ARGENTINA', 110, NULL, ARRAY[]::text[]),
  ('Zuccardi Q Chardonnay', 'Branco', 'ARGENTINA', 110, NULL, ARRAY[]::text[]),
  ('Zuccardi Q Tempranillo', 'Tinto', 'ARGENTINA', 110, NULL, ARRAY[]::text[]),
  ('Zuccardi Serie A Bonarda', 'Tinto', 'ARGENTINA', 90, NULL, ARRAY[]::text[]),
  ('Zuccardi Serie A Chardonnay Viogner', 'Branco', 'ARGENTINA', 90, NULL, ARRAY[]::text[]),
  ('Zuccardi Serie A Malbec', 'Tinto', 'ARGENTINA', 90, NULL, ARRAY[]::text[]),
  ('Almaviva 2023', 'Tinto', 'CHILE', 1397, NULL, ARRAY['new']),
  ('Almaviva EPU 2022', 'Tinto', 'CHILE', 559, NULL, ARRAY['new']),
  ('Echo Gran Reserva Cabernet Franc', 'Tinto', 'CHILE', 94, NULL, ARRAY['new']),
  ('Echo Gran Reserva Carignan', 'Tinto', 'CHILE', 94, NULL, ARRAY['new']),
  ('Echo Gran Reserva Carmenere', 'Tinto', 'CHILE', 94, NULL, ARRAY['new']),
  ('Echo Reserva Cabernet Sauvignon', 'Tinto', 'CHILE', 79, NULL, ARRAY['new']),
  ('Echo Reserva Carmenere', 'Tinto', 'CHILE', 79, NULL, ARRAY['new']),
  ('Echo Reserva Chardonnay', 'Branco', 'CHILE', 79, NULL, ARRAY['new']),
  ('Mapu Cabernet Sauvignon', 'Tinto', 'CHILE', 64, NULL, ARRAY['new']),
  ('Mapu Carmenere', 'Tinto', 'CHILE', 64, NULL, ARRAY['new']),
  ('Mapu Gran Reserva Carignan', 'Tinto', 'CHILE', 94, NULL, ARRAY['new']),
  ('Mapu Reserva Cabernet Sauvignon', 'Tinto', 'CHILE', 79, NULL, ARRAY['new']),
  ('Mapu Reserva Carmenere', 'Tinto', 'CHILE', 79, NULL, ARRAY['new']),
  ('Vik A Limited Edition Cabernet Sauvignon', 'Tinto', 'CHILE', 169, NULL, ARRAY['new']),
  ('Vik A Limited Edition Carmenere', 'Tinto', 'CHILE', 169, NULL, ARRAY['new']),
  ('Vik La Piu Belle Tinto', 'Tinto', 'CHILE', 395, NULL, ARRAY[]::text[]),
  ('Gafa Alvarinho Reserva', 'Branco', 'PORTUGAL', 80, NULL, ARRAY[]::text[]),
  ('Julian Reynolds Reserva 2018', 'Tinto', 'PORTUGAL', 229, 195, ARRAY['promo']),
  ('Cartuxa Colheita Tinto', 'Tinto', 'PORTUGAL', 259, NULL, ARRAY[]::text[]),
  ('Cartuxa Reserva Tinto', 'Tinto', 'PORTUGAL', 397, NULL, ARRAY[]::text[]),
  ('EA Cartuxa Branco 2024', 'Branco', 'PORTUGAL', 69, NULL, ARRAY[]::text[]),
  ('EA Cartuxa Rosé 2023', 'Rosé', 'PORTUGAL', 69, NULL, ARRAY[]::text[]),
  ('EA Cartuxa Tinto', 'Tinto', 'PORTUGAL', 69, NULL, ARRAY[]::text[]),
  ('Vinho Dos Santos Branco', 'Branco', 'PORTUGAL', 149, 119, ARRAY['promo']),
  ('Azeite Cartuxa EA 500ml', 'Azeite', 'PORTUGAL', 79, NULL, ARRAY['new'])
) as v(name, type, origin, price, promo, tags);

