-- Favoritos do cliente final, identificado só pelo telefone (sem login).
-- É um registro de interesse pro fornecedor ver, não uma conta de verdade —
-- por isso a RLS aqui é propositalmente simples: qualquer um pode inserir/
-- apagar (o "dono" é só quem sabe o próprio telefone), mas só o fornecedor
-- autenticado consegue LISTAR os favoritos do próprio catálogo.

create table if not exists customer_favorites (
  id bigint generated by default as identity primary key,
  supplier_id uuid not null references suppliers(id) on delete cascade,
  phone text not null,
  wine_id bigint not null references wines(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (supplier_id, phone, wine_id)
);

create index if not exists customer_favorites_supplier_idx on customer_favorites (supplier_id);

alter table customer_favorites enable row level security;

drop policy if exists "public adds favorites" on customer_favorites;
create policy "public adds favorites" on customer_favorites
  for insert with check (true);

drop policy if exists "public removes favorites" on customer_favorites;
create policy "public removes favorites" on customer_favorites
  for delete using (true);

drop policy if exists "supplier reads own customer favorites" on customer_favorites;
create policy "supplier reads own customer favorites" on customer_favorites
  for select using (
    supplier_id = (select id from suppliers where auth_user_id = auth.uid())
  );
